version: "3.8"

services:
  app:
    build: .
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      RUST_LOG: ${BACKEND_LOG_LEVEL}
      DB_CONNECTION: ${BACKEND_DB_CONNECTION}
    networks:
      - luma-network

networks:
  luma-network:
    name: ${DOCKER_NETWORK_NAME}
    external: true