version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: luma-postgres
      POSTGRES_DB: luma-postgres