# version: '3.9'

services:
  postgres:
    container_name: luma-postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - luma-network

volumes:
  pgdata:

networks:
  luma-network:
    name: ${DOCKER_NETWORK_NAME}
    external: true